
package pkgfinal.project.oop;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;


public class Frame5 extends javax.swing.JFrame {

    //create new frame5
    public Frame5() {
        initComponents();
    }
    
    Float caloryNeed;
    //note: Do NOT modify this code, content is generated by form editor
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        calMeal = new javax.swing.JLabel();
        Generate = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listMakanan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 223));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Daily Meal Plan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 330, 90));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Total calories on this meal plan is:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, -1, -1));

        calMeal.setBackground(new java.awt.Color(0, 0, 0));
        calMeal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        calMeal.setForeground(new java.awt.Color(255, 0, 0));
        calMeal.setText("0");
        jPanel1.add(calMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, -1, -1));

        Generate.setBackground(new java.awt.Color(182, 227, 136));
        Generate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Generate.setForeground(new java.awt.Color(255, 255, 255));
        Generate.setText("Generate");
        Generate.setBorder(null);
        Generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateActionPerformed(evt);
            }
        });
        jPanel1.add(Generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 140, 40));

        jSeparator2.setForeground(new java.awt.Color(200, 234, 166));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 234, 166), 5));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 184, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salad.png"))); // NOI18N
        jLabel4.setAlignmentY(0.0F);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 107, 107));

        reset.setBackground(new java.awt.Color(255, 255, 223));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(182, 227, 136));
        reset.setText("Reset");
        reset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(182, 227, 136), 2, true));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 710, 160, 60));

        jScrollPane2.setBackground(new java.awt.Color(255,255,255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        listMakanan.setBackground(new java.awt.Color(250,250,250));
        listMakanan.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        listMakanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu", "Calorie", "Carbs", "Fat", "Protein", "Fibre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listMakanan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        listMakanan.setGridColor(new java.awt.Color(0, 0, 0));
        listMakanan.setMaximumSize(new java.awt.Dimension(450, 0));
        listMakanan.setMinimumSize(new java.awt.Dimension(450, 0));
        listMakanan.setSelectionBackground(new java.awt.Color(250, 250, 250));
        listMakanan.setShowGrid(true);
        listMakanan.setShowVerticalLines(true);
        jScrollPane2.setViewportView(listMakanan);
        if (listMakanan.getColumnModel().getColumnCount() > 0) {
            listMakanan.getColumnModel().getColumn(0).setMinWidth(120);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 410, 450));

        jButton1.setBackground(new java.awt.Color(182, 227, 136));
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(182, 227, 136), 10, true));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 160, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateActionPerformed
        DefaultTableModel model = (DefaultTableModel) listMakanan.getModel();
        main.knapsack(caloryNeed);  
        if(model.getRowCount() == 0) {
            addTable(model);
           
            Float totalCal1 = 0f;
            Float totalCal2 = 0f;

            for (int i = 0; i < main.all1.size(); i++){
                totalCal1 += main.all1.get(i).calories;
            }
            for (int i = 0; i < main.all2.size(); i++){
                totalCal2 += main.all2.get(i).calories;
            }
            totalCal1 += totalCal2;
            calMeal.setText(totalCal1.toString());
            calMeal.setVisible(true);
        }
    }//GEN-LAST:event_GenerateActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        main.all1.clear();
        main.all2.clear();
        hitungBMR frm = new hitungBMR();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //create and display form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame5().setVisible(true);
            }
        });
    }
    
    public void addTable(DefaultTableModel model){
        Object rowData[] = new Object[6];
        for (int i = 0; i < main.all1.size(); i++){
            String a = String.valueOf(main.all1.get(i).calories) + " kcals";
            rowData[0] = main.all1.get(i).name;
            rowData[1] = a;
            rowData[2] = fullText(main.all1.get(i).carbs);
            rowData[3] = fullText(main.all1.get(i).fat);
            rowData[4] = fullText(main.all1.get(i).protein);
            rowData[5] = fullText(main.all1.get(i).fibre);
            model.addRow(rowData);
        }
        
        for (int i = 0; i < main.all2.size(); i++){
            String a = String.valueOf(main.all2.get(i).calories) + " kcals";
            rowData[0] = main.all2.get(i).name;
            rowData[1] = a;
            rowData[2] = fullText(main.all2.get(i).carbs);
            rowData[3] = fullText(main.all2.get(i).fat);
            rowData[4] = fullText(main.all2.get(i).protein);
            rowData[5] = fullText(main.all2.get(i).fibre);
            model.addRow(rowData);
        }
    }
    
    public String fullText(Float x) {
        String s = String.valueOf(x) + " g";
        return s;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Generate;
    private javax.swing.JLabel calMeal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable listMakanan;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
